# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo //Professional
  #  pod 'SuperPlayer', :path => '../SuperPlayer.podspec', :subspecs => ['Player']
  pod 'SuperPlayer', :path => '../SuperPlayer.podspec', :subspecs => ['Professional']

  pod 'MBProgressHUD'
end
